name: Update Image Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 1 UTC everyday
    - cron: "0 1 * * *"

jobs:
  update-readme:
    name: Update Image README
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/update-readme-image@main
        with:
          IMG_ALT: Image ALT
          IMG_PATH: ''
          IMG_REPOSITORY: aenichols/animoos
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          README_REPOSITORY: aenichols/animoos
